# File: azure-pipelines.yml

name : 7.1$(Rev:.r)

# TRIGGER WHEN WE CHECK IN CODE
trigger: 
- main

pool:
    vmImage: 'windows-latest'
    #name: 'Default'

variables:
#  packageName: 'artifact-boostdc-demo'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  solutionPath: "**/*.sln"
  vstsFeedName: 'f9a81605-0a01-468c-a4f3-521dcb226926'  

steps:
- checkout: self

- task: UseDotNet@2
  displayName: 'Use DotNet 7.0.x'
  inputs:
    version: '7.0.x'

- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  displayName: "nuget restore"
  inputs:
    command: 'restore'
    feedsToUse: 'select'
    vstsFeed: '$(vstsFeedName)'

- task: VSBuild@1
  displayName: 'VS Build'
  inputs:
    solution: '$(solutionPath)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(build.artifactStagingDirectory)\WebApp.zip" /p:DeployIisAppPath="Default Web Site"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'netcore pack'
  inputs:
    command: 'pack'
    packagesToPack: '**/*.csproj'
    includesymbols: true
    includesource: true
    versioningScheme: 'byEnvVar'
    versionEnvVar: 'Build.BuildNumber'

# - task: NuGetCommand@2
#   inputs:
#     command: 'pack'
#     packagesToPack: '**/BoostDC.Web.csproj'
#     versioningScheme: 'byEnvVar'
#     versionEnvVar: 'Build.BuildNumber'
#     includeSymbols: true

- task: NuGetCommand@2
  displayName: 'nuget push'
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
    nuGetFeedType: 'internal'    
    publishVstsFeed: '$(vstsFeedName)'
    allowPackageConflicts: true

# - task: UniversalPackages@0
#   displayName: 'universal publish'
#   inputs:
#     command: 'publish'
#     publishDirectory: '$(Build.ArtifactStagingDirectory)'
#     feedsToUsePublish: 'internal'
#     vstsFeedPublish: '$(vstsFeedName)'
#     vstsFeedPackagePublish: '$(packageName)'
#     versionOption: 'patch'